env:
  mocha: true

plugins:
  - "prettier"
  - "mocha"

extends:
  - "standard"
  - "prettier"

parserOptions:
  # Override eslint-config-standard, which incorrectly sets this to "module",
  # though that setting is only for ES6 modules, not CommonJS modules.
  sourceType: "script"

rules:
  prettier/prettier: "error"

  # Disable some rules from eslint:recommended.
  no-empty: ["error", { "allowEmptyCatch": true }]
  # Allow unused parameters. In callbacks, removing them seems to obscure
  # what the functions are doing.
  no-unused-vars: ["error", {"args": "none"}]

  # We keep whitespace cleaned up.
  no-trailing-spaces: "error"
  eol-last: "error"

  # These are not disabled by eslint-config-prettier
  spaced-comment: "off"
  standard/object-curly-even-spacing: "off"
  one-var: "off"

  # Our additions.
  no-var: "error"
  prefer-const: "error"
  strict: "error"
  no-console: "error"

  # Mocha.
  "mocha/handle-done-callback": "error"
  "mocha/no-global-tests": "error"
  "mocha/no-mocha-arrows": "error"
